version: '3.8'

services:
  db:
    image: postgres:17
    container_name: security-sketch-db
    environment:
      POSTGRES_DB: security_sketch
      POSTGRES_USER: sketch_user
      POSTGRES_PASSWORD: f0audfh8389r3z
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sketch_user -d security_sketch"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
